version: '3.8'  # Consider updating to '3' or '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: hellodoc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: saketh123
      MYSQL_DATABASE: hellodoc
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 10
    restart: always

  hellodoc:
    build: .
    ports:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hellodoc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: saketh123
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
